spring:
  datasource:
    url: jdbc:postgresql://mainline.proxy.rlwy.net:18726/railway
    username: postgres
    password: feyucQnPUcgBkuQGApEosJRgHOhVmJRE
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate